presubmits:
  - name: pull-PROJECT_NAME-test-unit
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/PROJECT_NAME"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kubestellar/infra/build:1.24.11-1
          command:
            - make
            - test
          env:
            - name: USE_GOTESTSUM
              value: "1"
          resources:
            requests:
              memory: 4Gi
              cpu: 2
