name: Feature Request
description: Suggest an idea for this project
title: "feature: "
labels:
  - kind/feature
body:
  - type: textarea
    id: problem
    attributes:
      label: Feature Description
      description: "Is your feature request related to a problem? A clear and concise description of what the problem is."
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
      placeholder: We can do [...]
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Assignment Instructions**

        To assign yourself to this issue, use the slash command:
        ```
        /assign
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
